In [50]:
import math

In [36]:
a=2
b=2
math.log(a,0.5)

-1.0

In [43]:
x=1
math.atan(x)/math.pi

0.25

In [49]:
a=3
math.factorial(0)

1

In [51]:
import numpy as np 

In [53]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [54]:
type(a)

numpy.ndarray

In [55]:
a.shape

(3,)

In [57]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
b.shape

(2, 3)

In [61]:
a = np.zeros((3,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [68]:
b = np.ones((3,5,4))
b

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [69]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [70]:
np.empty((3,3))

array([[4.67296746e-307, 1.69121096e-306, 7.56598449e-307],
       [1.89146896e-307, 7.56571288e-307, 3.11525958e-307],
       [1.24610723e-306, 1.29061142e-306, 5.53353523e-322]])

In [71]:
np.empty((3,2))

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 7.56598449e-307],
       [1.89146896e-307, 7.56571288e-307]])

In [75]:
a = np.arange(20,30,2)
a

array([20, 22, 24, 26, 28])

In [76]:
a = np.arange(1,0,-0.1)
a

array([1. , 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1])

In [77]:
a = np.arange(1,10,0.001)
print(a)

[1.    1.001 1.002 ... 9.997 9.998 9.999]


In [78]:
np.set_printoptions(threshold = 10000, precision = 2)
print(a)

[ 1.    1.    1.    1.    1.    1.    1.01  1.01  1.01  1.01  1.01  1.01
  1.01  1.01  1.01  1.01  1.02  1.02  1.02  1.02  1.02  1.02  1.02  1.02
  1.02  1.02  1.03  1.03  1.03  1.03  1.03  1.03  1.03  1.03  1.03  1.03
  1.04  1.04  1.04  1.04  1.04  1.04  1.04  1.04  1.04  1.04  1.05  1.05
  1.05  1.05  1.05  1.05  1.05  1.05  1.05  1.05  1.06  1.06  1.06  1.06
  1.06  1.06  1.06  1.06  1.06  1.06  1.07  1.07  1.07  1.07  1.07  1.07
  1.07  1.07  1.07  1.07  1.08  1.08  1.08  1.08  1.08  1.08  1.08  1.08
  1.08  1.08  1.09  1.09  1.09  1.09  1.09  1.09  1.09  1.09  1.09  1.09
  1.1   1.1   1.1   1.1   1.1   1.1   1.1   1.1   1.1   1.1   1.11  1.11
  1.11  1.11  1.11  1.11  1.11  1.11  1.11  1.11  1.12  1.12  1.12  1.12
  1.12  1.12  1.12  1.12  1.12  1.12  1.13  1.13  1.13  1.13  1.13  1.13
  1.13  1.13  1.13  1.13  1.14  1.14  1.14  1.14  1.14  1.14  1.14  1.14
  1.14  1.14  1.15  1.15  1.15  1.15  1.15  1.15  1.15  1.15  1.15  1.15
  1.16  1.16  1.16  1.16  1.16  1.16  1.16  1.16  1

In [79]:
np.set_printoptions(threshold=1000, precision=8) # вернем параметры по умолчанию
print(a)

[1.    1.001 1.002 ... 9.997 9.998 9.999]


In [80]:
a = np.array([20, 30, 40, 50])
a

array([20, 30, 40, 50])

In [82]:
b = np.arange(4)
b

array([0, 1, 2, 3])

In [83]:
c = a+b
c

array([20, 31, 42, 53])

In [86]:
c = a - b
c

array([20, 29, 38, 47])

In [87]:
c = a*b
c

array([  0,  30,  80, 150])

In [88]:
c = a/b
c

C:\Users\Slava\AppData\Local\Temp\ipykernel_11744\4141246561.py:1: RuntimeWarning: divide by zero encountered in divide
  c = a/b


array([        inf, 30.        , 20.        , 16.66666667])

In [90]:
np.inf + np.inf

inf

In [92]:
-1*np.inf

-inf

In [93]:
np.inf - np.inf

nan

In [94]:
a ** b

array([     1,     30,   1600, 125000])

In [95]:
a%b

C:\Users\Slava\AppData\Local\Temp\ipykernel_11744\1820107994.py:1: RuntimeWarning: divide by zero encountered in remainder
  a%b


array([0, 0, 0, 2])

In [96]:
a**3

array([  8000,  27000,  64000, 125000])

In [97]:
2**b

array([1, 2, 4, 8])

In [101]:
a = np.ones((3,1))
b = 2*np.transpose(a)
print(a.shape, b.shape)
print(b)
print(a)

(3, 1) (1, 3)
[[2. 2. 2.]]
[[1.]
 [1.]
 [1.]]


In [99]:
a*b

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [100]:
b*a

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [103]:
a=3*np.ones((4,4))
b=-1*np.ones((4,1))
c=a+b
c

[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]] [[-1.]
 [-1.]
 [-1.]
 [-1.]]


array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [104]:
c=5*np.cos(a) 
c

array([[-4.94996248, -4.94996248, -4.94996248, -4.94996248],
       [-4.94996248, -4.94996248, -4.94996248, -4.94996248],
       [-4.94996248, -4.94996248, -4.94996248, -4.94996248],
       [-4.94996248, -4.94996248, -4.94996248, -4.94996248]])

In [105]:
np.round(c,2)

array([[-4.95, -4.95, -4.95, -4.95],
       [-4.95, -4.95, -4.95, -4.95],
       [-4.95, -4.95, -4.95, -4.95],
       [-4.95, -4.95, -4.95, -4.95]])

In [106]:
np.floor(c)

array([[-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.]])

In [107]:
np.ceil(c)

array([[-4., -4., -4., -4.],
       [-4., -4., -4., -4.],
       [-4., -4., -4., -4.],
       [-4., -4., -4., -4.]])

In [108]:
np.fix(c)

array([[-4., -4., -4., -4.],
       [-4., -4., -4., -4.],
       [-4., -4., -4., -4.],
       [-4., -4., -4., -4.]])

In [117]:
a = np.array([[1, 2, 3], [4, 1, 6]]) 
a

array([[1, 2, 3],
       [4, 1, 6]])

In [110]:
np.sum(a)

np.int64(21)

In [112]:
a.sum()

np.int64(21)

In [113]:
a.min()


np.int64(1)

In [114]:
a.max()

np.int64(6)

In [121]:
a.sum(axis=1)

array([ 6, 11])

In [122]:
a.sum(axis=0)

array([5, 3, 9])

In [124]:
a = np.arange(10) ** 3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [125]:
a[4]

np.int64(64)

In [126]:
a[3:5]

array([27, 64])

In [127]:
a[[3,7]]

array([ 27, 343])

In [128]:
a[[7,3]]

array([343,  27])

In [129]:
a[[3,3]]

array([27, 27])

In [130]:
a[3:5] = 2 
a

array([  0,   1,   8,   2,   2, 125, 216, 343, 512, 729])

In [131]:
a[::-1]

array([729, 512, 343, 216, 125,   2,   2,   8,   1,   0])

In [132]:
b = np.array([[ 0,  1,  2,  3],
            [10, 11, 12, 13],
            [20, 21, 22, 23],
            [30, 31, 32, 33],
            [40, 41, 42, 43]])
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [133]:
b[2,3]

np.int64(23)

In [134]:
b[(2,3)]

np.int64(23)

In [135]:
b[[2,3]]

array([[20, 21, 22, 23],
       [30, 31, 32, 33]])

In [136]:
b[[2,3],3]

array([23, 33])

In [137]:
b[[2,3],[2,3]]

array([22, 33])

In [138]:
b[2:3, 2:3]

array([[22]])

In [143]:
b[2:4, 1:4]

array([[21, 22, 23],
       [31, 32, 33]])

In [144]:
b[2][3]

np.int64(23)

In [147]:
b[::,2]

array([ 2, 12, 22, 32, 42])

In [148]:
b[1:3, : : ]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [169]:
b[2:3,0]

array([20])

In [172]:
e=np.ones((2,3,4,2,3,4))
e[...,2]

array([[[[[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]]]],



       [[[[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1

In [173]:
a = np.array(([[0, 1, 2], [10, 12, 13]], [[100, 101, 102], [110, 112, 113]]))
a

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [174]:
a.shape

(2, 2, 3)

In [175]:
for row in a:
   print(row)
   print(' ')

[[ 0  1  2]
 [10 12 13]]
 
[[100 101 102]
 [110 112 113]]
 


In [176]:
for el in a.flat:
    print(el)

0
1
2
10
12
13
100
101
102
110
112
113


In [178]:
a

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [179]:
a.ravel() 

array([  0,   1,   2,  10,  12,  13, 100, 101, 102, 110, 112, 113])

In [180]:
a.shape = (6, 2) 
a

array([[  0,   1],
       [  2,  10],
       [ 12,  13],
       [100, 101],
       [102, 110],
       [112, 113]])

In [181]:
a.transpose()  


array([[  0,   2,  12, 100, 102, 112],
       [  1,  10,  13, 101, 110, 113]])

In [183]:
a.reshape((3, 4)) 

array([[  0,   1,   2,  10],
       [ 12,  13, 100, 101],
       [102, 110, 112, 113]])

In [184]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
np.vstack((a, b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [185]:
np.hstack((a, b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [186]:
np.column_stack((a, b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [187]:
np.row_stack((a, b))

C:\Users\Slava\AppData\Local\Temp\ipykernel_11744\2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [189]:
a = np.arange(12).reshape((2, 6))
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [190]:
np.hsplit(a, 3) 

[array([[0, 1],
        [6, 7]]),
 array([[2, 3],
        [8, 9]]),
 array([[ 4,  5],
        [10, 11]])]

In [191]:
np.hsplit(a, (3, 4))

[array([[0, 1, 2],
        [6, 7, 8]]),
 array([[3],
        [9]]),
 array([[ 4,  5],
        [10, 11]])]

In [192]:
np.vsplit(a, 2)

[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]])]

In [193]:
import random
import numpy.random as rand


In [201]:
np.random.sample()

0.6009830221377729

In [210]:
a=-0
b=5
a+(b-a)*np.random.sample()

3.567018107532478

In [211]:
np.random.sample(5)

array([0.07729589, 0.84735789, 0.0949422 , 0.56727484, 0.02328935])

In [214]:
np.random.sample((1, 1, 4))

array([[[0.9900741 , 0.52498341, 0.37220145, 0.62594697]]])

In [222]:
np.random.randint(0, 3, 10)

array([2, 2, 2, 0, 0, 2, 0, 1, 1, 1], dtype=int32)

In [223]:
np.random.random_integers(0, 3, 10)

C:\Users\Slava\AppData\Local\Temp\ipykernel_11744\3188335668.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 3 + 1) instead
  np.random.random_integers(0, 3, 10)


array([1, 3, 0, 0, 3, 3, 2, 0, 0, 1], dtype=int32)

In [224]:
np.random.randint(0, 3, (2, 10))

array([[1, 0, 2, 0, 1, 1, 2, 0, 1, 2],
       [2, 2, 1, 0, 0, 0, 2, 0, 2, 0]], dtype=int32)

In [228]:
np.random.uniform(2, 8, (2, 10))

array([[5.36532018, 3.44937463, 6.29579024, 4.20142519, 7.45591762,
        4.19322355, 6.88491634, 7.16694265, 3.45529947, 4.37172713],
       [4.37583984, 7.28777489, 7.18985668, 3.84730545, 7.02336115,
        5.61443141, 4.11343608, 2.83023709, 6.29895205, 7.57765898]])

In [229]:
np.random.seed(1000)
np.random.random(10)

array([0.65358959, 0.11500694, 0.95028286, 0.4821914 , 0.87247454,
       0.21233268, 0.04070962, 0.39719446, 0.2331322 , 0.84174072])

In [230]:
np.random.seed(100) 
np.random.random(10)

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886,
       0.12156912, 0.67074908, 0.82585276, 0.13670659, 0.57509333])

In [231]:
np.random.seed(1000)
np.random.random(10)

array([0.65358959, 0.11500694, 0.95028286, 0.4821914 , 0.87247454,
       0.21233268, 0.04070962, 0.39719446, 0.2331322 , 0.84174072])